const $=id=>document.getElementById(id);
const state={items:[],selected:null,install:null};
const toast=m=>{const e=$('toast');e.textContent=m;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',3600)};
const active=()=>state.items.find(x=>x.id===state.selected)||null;
function renderTimeline(){const t=$('timeline');t.innerHTML='';for(const it of state.items){const b=document.createElement('button');b.className='chip'+(it.id===state.selected?' active':'');b.textContent=(it.type.startsWith('image')?'🖼 ':'🎞 ')+it.name;b.onclick=()=>{state.selected=it.id;show(it);renderTimeline()};t.appendChild(b)}}
function applyVisual(){const it=active();if(!it||!it.el)return;const s=+$('scale').value,r=+$('rotation').value,x=+$('x').value,y=+$('y').value;it.v={s,r,x,y};let f='';if($('look').value==='cinema')f='contrast(1.14) saturate(.88) brightness(.96)';if($('look').value==='vivid')f='contrast(1.08) saturate(1.25)';if($('look').value==='mono')f='grayscale(1) contrast(1.08)';it.el.style.filter=f;it.el.style.transform='translate('+(x-50)+'%,'+(y-50)+'%) scale('+s+') rotate('+r+'deg)'}
function show(it){const stage=$('stage');stage.querySelectorAll('video,img').forEach(n=>n.remove());$('empty').style.display='none';let e;if(it.type.startsWith('image')){e=new Image();e.src=it.url}else{e=document.createElement('video');e.src=it.url;e.controls=true;e.playsInline=true;e.loop=true}e.onload=e.onloadedmetadata=()=>applyVisual();stage.prepend(e);it.el=e;const v=it.v||{s:1,r:0,x:50,y:50};$('scale').value=v.s;$('rotation').value=v.r;$('x').value=v.x;$('y').value=v.y;applyVisual()}
function addFiles(files){for(const file of files){const it={id:crypto.randomUUID(),name:file.name,type:file.type,url:URL.createObjectURL(file),v:{s:1,r:0,x:50,y:50}};state.items.push(it);state.selected=it.id;show(it)}renderTimeline()}
function planFor(raw){const t=raw.toLowerCase(),p=[];if(/recort|isolar|sem fundo|remove.*fundo/.test(t))p.push('Isolar sujeito / remover fundo');if(/voar|voe|fly|volar/.test(t))p.push('Animar posição X/Y');if(/zoom|aproxim/.test(t))p.push('Animar escala / zoom');if(/girar|rotate|rotar/.test(t))p.push('Animar rotação');if(/sombra|shadow/.test(t))p.push('Aplicar sombra');if(/motion blur|desfoque de movimento/.test(t))p.push('Aplicar motion blur');if(/acompan|rastre|track/.test(t))p.push('Tracking / câmera acompanhando');if(/cinemat|film/.test(t))p.push('Look cinematográfico');if(/lenta|slow/.test(t))p.push('Câmera lenta');if(/aceler|fast/.test(t))p.push('Acelerar clipe');if(/melhor.*foto|enhance.*photo/.test(t))p.push('Melhorar Foto 1‑Tap');return p}
function applyDirector(){const it=active(),raw=$('prompt').value.trim();if(!it)return toast('Importe e selecione uma mídia primeiro.');if(!raw)return toast('Escreva o que deseja fazer.');const t=raw.toLowerCase(),p=planFor(raw);$('plan').innerHTML=p.length?p.map((x,i)=>'<div class="step">'+(i+1)+'. '+x+'</div>').join(''):'<div class="muted">Comando ainda não reconhecido.</div>';if(/voar|voe|fly|volar/.test(t)){let x=50,y=18;if(/direit/.test(t))x=82;if(/esquerd/.test(t))x=18;if(/baixo/.test(t))y=82;if(/cima|superior|alto/.test(t))y=18;$('x').value=x;$('y').value=y}if(/zoom|aproxim/.test(t))$('scale').value=1.45;if(/girar|rotate|rotar/.test(t))$('rotation').value=25;if(/cinemat|film/.test(t))$('look').value='cinema';if(/desapare|fade out|sumir/.test(t))it.el.style.opacity='.2';if(/motion blur|desfoque de movimento/.test(t))it.el.style.filter=(it.el.style.filter?it.el.style.filter+' ':'')+'blur(1.2px)';applyVisual();toast('Comando aplicado no preview. O plano mostra as operações previstas.')}
async function enhance(){const it=active();if(!it||!it.type.startsWith('image'))return toast('Selecione uma foto.');const img=new Image();img.onload=()=>{const max=4096,sc=Math.min(2,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.round(img.naturalWidth*sc),h=Math.round(img.naturalHeight*sc),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.filter='contrast(1.1) saturate(1.06)';ctx.drawImage(img,0,0,w,h);ctx.filter='none';c.toBlob(blob=>{const ni={id:crypto.randomUUID(),name:'Foto melhorada.jpg',type:'image/jpeg',url:URL.createObjectURL(blob),v:{s:1,r:0,x:50,y:50}};state.items.push(ni);state.selected=ni.id;show(ni);renderTimeline();toast('Foto melhorada localmente. 0 créditos.')},'image/jpeg',.94)};img.src=it.url}
function installHelp(){const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(state.install){state.install.prompt();state.install.userChoice.finally(()=>state.install=null);return}toast(ios?'iPhone: Safari → Compartilhar → Adicionar à Tela de Início → Abrir como App.':'Android: menu do Chrome → Instalar app / Adicionar à tela inicial.')}
$('importBtn').onclick=()=>$('file').click();$('file').onchange=e=>addFiles([...e.target.files]);$('applyBtn').onclick=applyDirector;$('enhanceBtn').onclick=enhance;$('installBtn').onclick=installHelp;for(const id of ['scale','rotation','x','y','look'])$(id).oninput=applyVisual;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.install=e;$('installBtn').textContent='⬇ Instalar app'});window.addEventListener('appinstalled',()=>{$('installBtn').textContent='✓ Instalado';toast('Viduara instalado.')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('installBtn').textContent='✓ Instalado';
if(new URLSearchParams(location.search).get('director'))setTimeout(()=>$('prompt').focus(),400);